import { studies } from "@/lib/portfolio";
import ObjectStudy from "@/components/observatory/ObjectStudy";
import DeliveryStudy from "@/components/observatory/DeliveryStudy";
function TransactionDrawing() {
  return <div className="transaction-drawing" role="img" aria-label="Invoice, inventory and customer ledger are updated inside one database transaction, then committed together."><div className="receipt"><span className="micro">Hardware Store ERP</span><strong>One sale.<br />Three records.</strong><div><span>Invoice</span><span>Created</span></div><div><span>Inventory</span><span>Updated</span></div><div><span>Customer ledger</span><span>Balanced</span></div><p>BEGIN <span>→</span> COMMIT</p></div><svg className="receipt-annotation" viewBox="0 0 350 110" aria-hidden="true"><path d="M35 5q-35 70 45 67h196m-15-9 17 9-17 10" /></svg><span className="handwritten transaction-note">Everything goes through.<br />Or nothing does.</span><span className="micro figure-bottom">PostgreSQL / atomic transaction</span></div>;
}
function WorkflowDrawing() {
  return <div className="workflow-drawing" role="img" aria-label="A request moves through approval and sourcing before a purchase order is released. Role and tenant checks guard transitions."><span className="micro">Procure-to-Pay / guarded transitions</span><div className="workflow-track">{["Purchase request", "Approval", "Sourcing", "PO release"].map((step,i) => <div key={step}><span className="workflow-index">{i+1}</span><span>{step}</span>{i<3 && <span className="workflow-connector" aria-hidden="true">↓</span>}</div>)}</div><div className="workflow-margin handwritten">Check the role.<br />Check the state.<br />Then move forward.</div><p className="micro workflow-foot">Tenant boundary · Role check · Valid state</p></div>;
}
export default function EngineeringStudies({ standalone = false }: { standalone?: boolean }) {
  return <div className={`engineering-studies${standalone ? " studies-standalone" : ""}`}>{studies.map((study,index) => <article className={`study study-${index}`} id={study.id} key={study.id}><div className="study-visual">{index === 0 ? <TransactionDrawing /> : index === 1 ? <WorkflowDrawing /> : <div className="satellite-study"><ObjectStudy kind="satellite" /><DeliveryStudy /></div>}</div><div className="study-copy"><p className="eyebrow">{study.type}</p><h3>{study.name}</h3><p className="study-thesis">{study.title}</p><p className="study-summary">{study.summary}</p><p className="stack">{study.stack}</p><details className="study-details"><summary>Inside the system <span aria-hidden="true">+</span></summary><div>{study.details.map(([title,description]) => <section key={title}><h4>{title}</h4><p>{description}</p></section>)}{study.link && <a className="text-link" href={study.link} target="_blank" rel="noopener noreferrer">{study.linkLabel} ↗</a>}</div></details><p className="study-date micro">{study.date}</p></div></article>)}</div>;
}
