import assert from "node:assert/strict";
import fs from "node:fs";
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || "playwright");
const origin = process.env.PORTFOLIO_URL || "http://127.0.0.1:3000";
const output = "docs/qa/journal";
fs.mkdirSync(output, { recursive: true });
const report = { checks: [], errors: [], screenshots: [] };
const check = (name, value) => { assert.ok(value, name); report.checks.push(name); };
const browser = await chromium.launch({ channel: "chrome", headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await context.newPage();
  page.on("pageerror", error => report.errors.push(error.message));
  const shot = async name => { await page.screenshot({ path: `${output}/${name}.png` }); report.screenshots.push(name); };
  const jump = async id => {
    await page.evaluate(id => { const e = document.getElementById(id); scrollTo({ top: e.getBoundingClientRect().top + scrollY - 30, behavior: "instant" }); }, id);
    await page.waitForTimeout(950);
  };
  const noOverflow = () => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth);
  await page.goto(origin, { waitUntil: "networkidle" });
  await page.waitForSelector('canvas[data-object-ready="satellite"]');
  check("Home has one h1 and main", await page.locator("h1").count() === 1 && await page.locator("main").count() === 1);
  check("Desktop fits the viewport", await noOverflow());
  await shot("home-desktop");
  await page.getByRole("slider", { name: "Satellite view angle" }).first().fill("90");
  check("Satellite control responds", await page.getByRole("slider", { name: "Satellite view angle" }).first().inputValue() === "90");
  await page.locator(".hero-satellite").getByRole("button", { name: "Still view" }).click();
  check("Still view removes the hero renderer", await page.locator(".hero-satellite canvas").count() === 0);
  await page.locator(".hero-satellite").getByRole("button", { name: "Enable 3D" }).click();
  await page.waitForSelector('.hero-satellite canvas[data-object-ready]');
  await jump("stack");
  await page.waitForSelector('canvas[data-object-ready="circuit"]');
  await page.getByRole("slider", { name: "Separate the layers" }).fill("0");
  await page.waitForTimeout(800);
  const together = await page.locator(".object-circuit .object-stage").screenshot();
  await page.getByRole("slider", { name: "Separate the layers" }).fill("100");
  await page.waitForTimeout(800);
  const apart = await page.locator(".object-circuit .object-stage").screenshot();
  check("Separating layers changes the rendered object", !together.equals(apart));
  await shot("stack-separated");
  await jump("hardware-erp");
  await page.locator("#hardware-erp summary").click();
  check("ERP detail contains transaction evidence", (await page.locator("#hardware-erp").innerText()).includes("FOR UPDATE"));
  await shot("erp-details");
  await page.locator("#hardware-erp summary").click();
  await jump("vartalaap");
  await page.getByLabel("Take recipient B offline").check();
  await page.getByRole("button", { name: "Send a sample message" }).click();
  check("One offline recipient does not cancel the other deliveries", (await page.locator(".delivery-status").textContent()).includes("A and C received"));
  check("Only two delivery nodes succeed", await page.locator(".delivered").count() === 2);
  await shot("independent-delivery");
  await jump("ground");
  await page.waitForSelector('canvas[data-object-ready="prism"]');
  await page.getByRole("slider", { name: "Prism view angle" }).fill("70");
  await page.locator(".quiet-discovery summary").click();
  check("Ram Naam has meaningful accessible text", (await page.locator(".quiet-discovery").innerText()).includes("holding everything together"));
  await shot("prism-and-ram");
  await jump("archive");
  const titles = await page.locator(".archive-record h3").allTextContents();
  for (const title of ["Shiv Cement Store", "AI-Powered Alexa Assistant", "Mythos AI Studio", "Foxpop.in", "MedScan AI", "URL Shortener", "Prompt Enhancer", "Serverless Notification System"]) check(`Project preserved: ${title}`, titles.includes(title));
  await page.getByRole("searchbox", { name: "Find a project" }).fill("DynamoDB");
  check("Archive search narrows projects", await page.locator(".archive-record").count() === 1);
  await page.getByRole("searchbox", { name: "Find a project" }).fill("nomatchingproject");
  await page.getByRole("button", { name: "Show every project" }).click();
  check("Search empty state restores all projects", await page.locator(".archive-record").count() === 8);
  await page.locator("#shiv-cement summary").click();
  await page.locator("#shiv-cement img").evaluate(img => img.decode());
  check("Project screenshot loads", await page.locator("#shiv-cement img").evaluate(img => img.naturalWidth > 0));
  check("Architecture link retained", await page.locator("#shiv-cement").getByRole("link", { name: "View architecture" }).getAttribute("href") === "/diagram-export-18-04-2026-22_29_24.png");
  await shot("archive");
  await page.keyboard.press("Control+k");
  check("Page finder opens with keyboard", await page.locator(".command-dialog").evaluate(e => e.open));
  await page.keyboard.press("Escape");
  check("Escape closes page finder", !await page.locator(".command-dialog").evaluate(e => e.open));
  for (const route of ["/work", "/about", "/blogs", "/blogs/aws-db", "/contact"]) {
    const response = await page.goto(origin + route, { waitUntil: "networkidle" });
    check(`${route} loads and fits`, response.status() === 200 && await noOverflow());
    check(`${route} has one h1`, await page.locator("h1").count() === 1);
    await shot(route.replaceAll("/", "-"));
  }
  await page.getByRole("button", { name: "Send message" }).click();
  check("Contact form validates empty fields", await page.locator(".field-error").count() === 3);
  await page.route("**/api/contact", route => route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ error: "Test transport unavailable" }) }));
  await page.getByLabel("Your name").fill("Portfolio QA");
  await page.getByLabel("Email address").fill("qa@example.com");
  await page.getByLabel("What are you thinking?").fill("Testing the form without sending a real message.");
  await page.getByRole("button", { name: "Send message" }).click();
  await page.locator(".contact-form [role=alert]").waitFor();
  check("Failed send preserves draft", (await page.getByLabel("What are you thinking?").inputValue()).includes("Testing"));
  await page.unroute("**/api/contact");
  await page.route("**/api/contact", route => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ message: "Test success" }) }));
  await page.getByRole("button", { name: "Send message" }).click();
  await page.waitForURL("**/thank-you");
  check("Successful mocked send reaches thanks", (await page.locator("h1").textContent()).includes("Thank you"));
  const pdf = await context.request.get(origin + "/amankeshridotcom.pdf");
  check("Resume download is the latest source", (await pdf.body()).equals(fs.readFileSync("amankeshridotcom.pdf")));
  await page.goto(origin + "/work#mythos", { waitUntil: "networkidle" });
  check("Direct project link opens the record", await page.locator("#mythos").evaluate(e => e.open));
  for (const width of [360, 390, 768, 1920]) {
    await page.setViewportSize({ width, height: width < 500 ? 844 : 1000 });
    await page.goto(origin, { waitUntil: "networkidle" });
    await page.waitForSelector('.hero-satellite canvas[data-object-ready]');
    check(`${width}px home has no overflow`, await noOverflow());
    await shot(`home-${width}`);
    if (width === 390) {
      await page.getByRole("button", { name: "Open navigation" }).click();
      check("Mobile navigation opens", await page.locator(".mobile-menu").evaluate(e => e.open));
      await shot("mobile-menu"); await page.keyboard.press("Escape");
      check("Mobile menu returns focus", await page.getByRole("button", { name: "Open navigation" }).evaluate(e => e === document.activeElement));
      for (const id of ["stack", "hardware-erp", "vartalaap", "ground", "archive"]) { await jump(id); await shot(`mobile-${id}`); check(`Mobile ${id} fits`, await noOverflow()); }
      for (const route of ["/work", "/about", "/blogs", "/blogs/aws-db", "/contact"]) { await page.goto(origin + route, { waitUntil: "networkidle" }); check(`Mobile ${route} fits`, await noOverflow()); await shot(`mobile${route.replaceAll("/", "-")}`); }
    }
  }
  check("No normal runtime errors", report.errors.length === 0);
  await context.close();
  const reduced = await browser.newContext({ reducedMotion: "reduce", viewport: { width: 390, height: 844 } });
  const rp = await reduced.newPage(); const requests = [];
  rp.on("request", r => requests.push(r.url())); await rp.goto(origin, { waitUntil: "networkidle" });
  check("Reduced motion avoids WebGL and models", await rp.locator("canvas").count() === 0 && !requests.some(url => url.endsWith(".glb")));
  check("Reduced motion still contains the illustration", await rp.locator(".hero-landscape img").evaluate(img => img.complete && img.naturalWidth > 0));
  await rp.screenshot({ path: `${output}/reduced-motion.png` }); await reduced.close();
  const unsupported = await browser.newContext();
  await unsupported.addInitScript(() => { const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function(type,...args) { return String(type).includes("webgl") ? null : original.call(this,type,...args); }; });
  const up = await unsupported.newPage(); await up.goto(origin, { waitUntil: "networkidle" });
  await up.waitForSelector('.hero-satellite [data-object-mode="still"]');
  check("Unsupported WebGL preserves rendered fallback", await up.locator(".hero-satellite img").evaluate(img => img.complete && img.naturalWidth > 0)); await unsupported.close();
  const missing = await browser.newContext(); await missing.route("**/satellite.glb", route => route.abort());
  const mp = await missing.newPage(); await mp.goto(origin, { waitUntil: "networkidle" }); await mp.waitForSelector('.hero-satellite [data-object-mode="still"]');
  check("Missing model retains content and fallback", await mp.locator("h1").isVisible()); await missing.close();
  const loss = await browser.newContext(); const lp = await loss.newPage(); await lp.goto(origin, { waitUntil: "networkidle" }); await lp.waitForSelector('.hero-satellite canvas[data-object-ready]');
  await lp.locator(".hero-satellite canvas").evaluate(c => c.getContext("webgl2").getExtension("WEBGL_lose_context").loseContext());
  await lp.waitForSelector('.hero-satellite [data-object-mode="still"]'); check("Context loss returns to illustrated view", await lp.locator(".hero-satellite canvas").count() === 0); await loss.close();
  const nojs = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } });
  const np = await nojs.newPage(); await np.goto(origin); check("No JavaScript retains every project", await np.locator(".archive-record").count() === 8); await nojs.close();
  fs.rmSync(`${output}/failure.json`, { force: true });
  fs.writeFileSync(`${output}/verification.json`, JSON.stringify(report,null,2));
  console.log(JSON.stringify({ passed: report.checks.length, runtimeErrors: report.errors, report: `${output}/verification.json` },null,2));
} catch(error) {
  fs.writeFileSync(`${output}/failure.json`,JSON.stringify({...report,error:error.stack},null,2)); throw error;
} finally { await browser.close(); }
